// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoAbcNYbv4HmoHYDzYbL_nPY1VuZ4thrw',
    appId: '1:1022453570559:web:6c67f9027353e2904d65ca',
    messagingSenderId: '1022453570559',
    projectId: 'grade-learn-07',
    authDomain: 'grade-learn-07.firebaseapp.com',
    storageBucket: 'grade-learn-07.firebasestorage.app',
    measurementId: 'G-0SR8LR6M60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0GR2gDrgjKpGrNNvhIeVImes9A1eAlbM',
    appId: '1:1022453570559:android:c56e094408486ac34d65ca',
    messagingSenderId: '1022453570559',
    projectId: 'grade-learn-07',
    storageBucket: 'grade-learn-07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3lG539m3HdSz9gsj-MSm0dtkMOPRYieo',
    appId: '1:1022453570559:ios:d7d2ec77a42a4cc94d65ca',
    messagingSenderId: '1022453570559',
    projectId: 'grade-learn-07',
    storageBucket: 'grade-learn-07.firebasestorage.app',
    iosClientId: '1022453570559-nr9e696pg8j4eo1vjq8p9o8pb9hjocof.apps.googleusercontent.com',
    iosBundleId: 'com.example.gradeLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3lG539m3HdSz9gsj-MSm0dtkMOPRYieo',
    appId: '1:1022453570559:ios:d7d2ec77a42a4cc94d65ca',
    messagingSenderId: '1022453570559',
    projectId: 'grade-learn-07',
    storageBucket: 'grade-learn-07.firebasestorage.app',
    iosClientId: '1022453570559-nr9e696pg8j4eo1vjq8p9o8pb9hjocof.apps.googleusercontent.com',
    iosBundleId: 'com.example.gradeLearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoAbcNYbv4HmoHYDzYbL_nPY1VuZ4thrw',
    appId: '1:1022453570559:web:ec22562c054975474d65ca',
    messagingSenderId: '1022453570559',
    projectId: 'grade-learn-07',
    authDomain: 'grade-learn-07.firebaseapp.com',
    storageBucket: 'grade-learn-07.firebasestorage.app',
    measurementId: 'G-3X0NHTTV01',
  );

}